### ISSUE TITLE
Missing Files

### ISSUE THREAD

**Issue by jmanhype** [thinkwee/iAgents#2]
It wont allow me to log in or register. When i register it alerts me that register.html is missing

**Comment by thinkwee** [comment]
Could you please provide more details? I have tested it on my computer and the login/register works well. There is no register.html since login and register functions are all included in ``templates/login.html``

1. here. i try to register with the name "newuser"
<img width="372" alt="image" src="https://github.com/user-attachments/assets/759bc82e-aa5f-447b-a853-414df32ce9a0">

2. and i successfully login with "newuser" after registered
<img width="577" alt="image" src="https://github.com/user-attachments/assets/7c65508a-3519-4ec3-a9e7-279e612e62ea">

**Comment by thinkwee** [comment]
Please reopen this issue if you still have a problem.
